### PR TITLE
Bump ruby-build version to v20221225

### PR DESCRIPTION
**Pull request by vlazar**

### CODE REVIEW

**Comment by alperakgun** [comment]
Thanks @vlazar  - will this make Ruby 3.2.0 available to install in asdf?

**Comment by vlazar** [comment]
> Thanks @vlazar - will this make Ruby 3.2.0 available to install in asdf?

@alperakgun Yes.

Meanwhile you can install Ruby 3.2.0 referencing [this ruby-build commit](https://github.com/rbenv/ruby-build/commit/9d92a697d24d9625a0f4d00b76e46224a05ba13f) directly
```
ASDF_RUBY_BUILD_VERSION=9d92a697d24d9625a0f4d00b76e46224a05ba13f asdf install ruby 3.2.0
```

**Review by tachyons — APPROVED** [review]

**Comment by jaysonvirissimo** [comment]
NOTE: This fails on Apple M1/macOS Ventura 13.0.1 if you don't already have `psych` for YAML output. The workaround is to first install `libyaml`. If you're using Homebrew, it's as simple as:

```
brew update && brew upgrade
brew install libyaml
ASDF_RUBY_BUILD_VERSION=9d92a697d24d9625a0f4d00b76e46224a05ba13f asdf install ruby 3.2.0
```

**Comment by n-rodriguez** [comment]
> Meanwhile you can install Ruby 3.2.0 referencing [this ruby-build commit](https://github.com/rbenv/ruby-build/commit/9d92a697d24d9625a0f4d00b76e46224a05ba13f) directly

Tested here, it works great! thank you!

**Comment by n-rodriguez** [comment]
Hi there! Merge?

**Comment by n-rodriguez** [comment]
ping @tachyons

**Comment by n-rodriguez** [comment]
@Stratus3D Thank you!

**Comment by dirksierd** [comment]
> NOTE: This fails on Apple M1/macOS Ventura 13.0.1 if you don't already have `psych` for YAML output. The workaround is to first install `libyaml`. If you're using Homebrew, it's as simple as:
> 
> ```
> brew update && brew upgrade
> brew install libyaml
> ASDF_RUBY_BUILD_VERSION=9d92a697d24d9625a0f4d00b76e46224a05ba13f asdf install ruby 3.2.0
> ```

I already has libyaml installed (did a reinstall though, to be sure), but I still get this psych-error. Not sure how to fix.

```bash
Generating RDoc documentation
/private/var/folders/1f/6_bbpt_96x31_nlntjz0c3vr0000gn/T/ruby-build.20221228170919.59285.ssVGNI/ruby-3.2.0/lib/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
uh-oh! RDoc had a problem:
cannot load such file -- psych

run with --debug for full backtrace
make: *** [rdoc] Error 1
```

**Pull request merged**
