### PR TITLE
[Fixes #239] Fixes testing for existing ruby version in install script.

### LINKED ISSUE #239: Can't install any version (without using a workaround)
Hello, I wanted to report something that I thought seemed unexpected.

- I've pulled down the latest versions of asdf-vm/asdf-ruby (tried with both master branch and latest release branch)
- I'm using a new/clean terminal window
- macOS m1, zsh
- I tried this with both 3.0.3 and 2.75

image

I found my ruby-build version locally and it seems correct/current/expected:

image

I did a _little_ bit of debugging on [these lines](https://github.com/asdf-vm/asdf-ruby/blob/c684fadea52284583802dfaf7705c92a78a085b5/bin/install#L35-L37)

`$matching_version` actually returns `3.0.3` correctly, but it fails inside of that if block.

I resolved it by deleting the if block (because I knew the version was correct). I'm not sure what the correct fix should be or the root cause and I wasn't able to trace with the `-n` flag in that statement was doing but I'm wondering if it's not related to either zsh or my bash version.

`/usr/bin/env bash` returns the following (this looks like my homebrew bash):

```
GNU bash, version 5.1.8(1)-release (aarch64-apple-darwin20.4.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

A few other things might be relevant:

- I also upgraded homebrew bash to 5.1.12 and have the same issue
- I tried with an older version of ruby, 2.7.4

I tried the `-n` snippet in zsh and bash and both always seem to exit early:

image

image

I'm not an expert in bash, but I the docs [here](https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html) say that `-n` is "true if the string is non-zero" so I think this might be a bug.

I'm happy to do a small pull request on this, but I didn't see anyone else report an issue so I'm not sure if this is a bug or if it's me (I have some custom zsh/shell stuff setup). Was hoping someone can confirm this behavior.

Update: Just noticed this other behavior as well

```
asdf install ruby 2.7.4 # returns "Version not found", but it definitely is
asdf install ruby 3.0.5 # silent exit
```

### PR DESCRIPTION
**Pull request by il-santo**
Fixes #239 .

### CODE REVIEW

**Review by tute — APPROVED** [review]
Thanks!

**Comment by jaydorsey** [comment]
This fixes the thing that's broken now but not the actual failure.

Doesn't need to block the merge here but when I test this locally `asdf install ruby 3.0.5` just returns quietly with no error message

**Comment by jaydorsey** [comment]
The reason it's failing is the `set -e` near the top. Grep returns with a non-zero exit code when `grep "$version"` fails to find the version, and the `-e` flag tells bash to exit immediately on a non-zero exit code

I think this is fine to merge to fix the immediate issue of not being able to install anything. Long term it might be useful to drop the `-e` flag. I'm not sure if we can suppress the non-zero exit code in grep?

**Comment by il-santo** [comment]
Yes, I'm with @jaydorsey : the main issue is not being able to upgrade ruby (and there are 3 CVEs pending on 3.0.2...). Having a warning for asking to install a non existing version is IMHO a minor issue and you can fix it in the long term.

**Review by kerolloz — APPROVED** [review]

**Comment by avlye** [comment]
Thanks! This worked for me. 😊

**Review by icyleaf — APPROVED** [review]

**Comment by jaydorsey** [comment]
@il-santo If you add this to your PR, it should fix the issue completely (I think):

```
  set +e
  matching_version=$(is_version_valid "$version")
  set -e
```

It temporarily tells the script not to exit when the `is_version_valid` command fails to find a match on the last grep (e.g. someone tried to install a version that isn't found by ruby-build).

image

**Comment by il-santo** [comment]
@jaydorsey I merged your PR, so this PR can be merged too. Thanks! 😉

**Comment by Stratus3D** [comment]
Thanks for the fix @il-santo !

**Comment by Stratus3D** [comment]
And thanks for the `set -e` fix @jaydorsey !

**Pull request merged**
