### PR TITLE
added support for pseudo-gemsets a la rvm

### PR DESCRIPTION
**Pull request by sjaveed**
install a gemset like so:

asdf install ruby 2.5.1@my_gemset

This will install ruby 2.5.1 in:
  ~/.asdf/installs/ruby/2.5.1@my_gemset

use a gemset in the following ways:

1. add a .ruby-gemset file alongside a .ruby-version file like so:

.ruby-version contains "2.5.1"
.ruby-gemset contains "sekret_project"

This will result in using the ruby 2.5.1 installed in:
  ~/.asdf/installs/ruby/2.5.1@sekret_project

2. add gemset information directly to the .ruby-version file:

.ruby-version contains "2.5.1@public"

This will result in using the ruby 2.5.1 installed in:
  ~/.asdf/installs/ruby/2.5.1@public

3. add a .tool-versions file like so:

.tool-versions contains "ruby 2.5.1@another_sekret"

This will result in using the ruby 2.5.1 installed in:
  ~/.asdf/installs/ruby/2.5.1@another_sekret

### CODE REVIEW

**Comment by sjaveed** [comment]
Sure thing!  You could probably cherry-pick that last commit to get builds passing again.  I’m not sure how to add a test for this new functionality though.

**Comment by sjaveed** [comment]
Hey @Stratus3D I see you've cherry-picked the build fix to get travis builds passing!  I'm glad that worked!  Any word on the remainder of the pull request?

**Comment by kronn** [comment]
I for one would be very much looking forward to this. Essentially, this is the main blocker I have in switching from RVM to asdf.

**Comment by Stratus3D** [comment]
Sorry for the late reply here. Merging this PR now.

**Comment by Stratus3D** [comment]
Actually, now I'm contemplating whether this is needed at all now. It's 2020 and Bundler has been around for a long time. It might be better to encourage those who still need gemsets to update their legacy apps to use Bundler instead. https://meatherly.github.io/ruby/2013/08/19/gemsets-are-dead-start-using-bundler/

**Comment by sjaveed** [comment]
I think there’s still a use case for gemsets but I’m on a phone so can’t expand on it further.  However, I ended up going back to RVM so your call on how you want to handle this.

**Comment by Stratus3D** [comment]
Closing for now as I don't think this is something we want to pursue now. Thanks for the PR @sjaveed . Sorry for taking so long to getting around to reviewing this.

**Comment by kronn** [comment]
Yes, Bundler is around and will stay with us. I like how it reduces the problem of maintaining and finding the right versions of gems. I like also how gemsets reduce the problem which version of any gem I run. And I like to use tools to recude superfluous typing. Just like I use asdf to select the right ruby instead of prefixing every command with ENV-Vars and full paths, I like how rvm reduces the need to type `bundle exec` before every command. ENV-Vars are, to echo your argument, around for an even longer argument. 

The apps I have are of course using bundler, my terminal-life is however dependent on gemsets. I see the aforementioned support for gemsets as a good thing.

**Comment by lpez** [comment]
I would also be interested in gemsets being added

**Comment by kronn** [comment]
Personally, I now use direnv to add the `bin`-directory to the `PATH` when I am in den project-dir. Together with binstubs located in aforementioned `bin`-dir, I very very seldomly type `bundle exec`. I mostly type it to generate the binstubs in the firstplace or to fill the binstub with the correct incantation. For example, `bin/rspec` contains `bundle exec spring rspec`, which is something I wholeheartedly refuse to ever type out manually just to cater the various isolation and preloading needs.

While I still see the value of this, I have found a working workaround around (pun intended) the loading issues of outdated rake-versions.

**Pull request closed without merging**
