### PR TITLE
allow to apply custom patches during install (fixes #15)

### LINKED ISSUE #15: How can I apply patch?
I'm trying to install older versions of Ruby, but there is widely known ssl bug when compile, with rvm or rbenv, this can be solved by passing argument --patch when installing.

How can I do this with asdf-ruby?

### PR DESCRIPTION
**Pull request by breunigs**
My preliminary testing is done, but I will give it a more thorough spin tomorrow. In the meantime, please take a look. If you see a better way to resolve relative paths, that'd be nice. The patch introduces a couple of new dependencies: `grep`, `patch` and it requires a Bash 3+ something, due to the regex operator.

Cheers
Stefan

### CODE REVIEW

**Comment by breunigs** [comment]
Thanks for taking a look! Good point about spellcheck, I fixed the issues (apart from the one that suggest to do `local somevar` and `somevar="bla"` on separate lines to avoid shadowing).

I tested the previous iteration of my patch on Linux today and it works splendidly. I will give it a run on OSX soon.

**Comment by breunigs** [comment]
I tested the latest version of this branch on OSX and it also works there. So I consider this ready to be merged. If there's issues cropping up with this, please do tag me and I'll take a look and/or provide a fix.

**Comment by Stratus3D** [comment]
Since the code won't do anything if the `RUBY_APPLY_PATCHES` variable is not set I think this is a safe change to make. If you discover any bugs with this functionality please open an issue or create another PR. Thanks!

**Comment by paulodiovani** [comment]
I would prefer a `--path` options, just as in `ruby-build`, but this may work.
@thiagoa Mind taking a look, if you're still using `asdf`?

**Pull request merged**
