### PR TITLE
Update ruby-build to 20190130

### PR DESCRIPTION
**Pull request by gmcabrita**
This will allow installing Ruby 2.6.1

### CODE REVIEW

**Comment by mtchavez** [comment]
Any update on merging this as 2.6.1 has a critical bug fix for 2.6.0?

**Comment by mattbrictson** [comment]
I installed manually as a workaround:

```
$ brew install ruby-build
$ ruby-build 2.6.1 ~/.asdf/installs/ruby/2.6.1
$ cat ~/.default-gems | xargs ~/.asdf/installs/ruby/2.6.1/bin/gem install
```

**Comment by dazuma** [comment]
@Stratus3D

**Comment by psantos10** [comment]
@Stratus3D maybe you should add (look for) someone else to help to maintain this repo

**Comment by devinrm** [comment]
If you're looking for a maintainer, I'd be happy to maintain this repo.

**Comment by gylaz** [comment]
> I installed manually as a workaround:

Might be easier to just edit `~/.asdf/plugins/ruby/lib/utils.sh` and update `RUBY_BUILD_VERSION` to `20190130`.

**Comment by psantos10** [comment]
I did the same as @gylaz ..

**Comment by devinrm** [comment]
I changed this line in https://github.com/asdf-vm/asdf-ruby/blob/master/lib/utils.sh#L1 to be an environment variable that I export in my shell so I can just update it from my zshrc now. Might be worth a PR that checks for the variable or whatever the current hard-coded version is so that this isn't a blocker anymore.

**Comment by isavegas** [comment]
For now, I added an extremely simple git hook under `.git/hooks/post-merge` that updates my ruby-build version. After looking through the mechanics of asdf and asdf-ruby, I can't think of a way to keep the user's ruby-build updated without either adding some kind of hook to asdf itself or attempting to update ruby-build with every call to it, which doesn't sound very good for performance.

Perhaps the best course of action would be to ask for asdf's plugin-add and plugin-update commands to run `bin/post-update` for the relevant plugin, if it exists?

**Comment by tessi** [comment]
many ❤️ @Stratus3D 

I just wondered why i can't install 2.6.1 when I saw this being merged just in the very second I finished reading this thread.

this is my shout out to you thanking for maintaining this plugin 🙏

**Comment by Stratus3D** [comment]
Sorry all, I was on vacation when this PR came in. I'll see what I can do about adding another maintainer to this project so this doesn't happen again. Currently 5 people have permission to merge PRs here.

**Pull request merged**
