### PR TITLE
Update install to fetch 1.9 rubies from different directory where required

### LINKED ISSUE #29: Ruby 1.9.3-p194 won't install
Running asdf install for 1.9.3-p194 is consistently throwing the error below
```
asdf install ruby 1.9.3-p194
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168  100   168    0     0    226      0 --:--:-- --:--:-- --:--:--   226

gzip: stdin: not in gzip format
```

### PR DESCRIPTION
**Pull request by RyanMacG**
Fixes #29

### CODE REVIEW

**Comment by RyanMacG** [comment]
Worth noting we could take a similar approach to the 2.1 issue that was reported, just wanted to put this forward first

**Comment by RyanMacG** [comment]
@Stratus3D @HashNuke any thoughts?

**Comment by Stratus3D** [comment]
@RyanMacG hey, sorry it's taken so long for me to get to this. I only have one concern:

`ruby_1_9=$ruby_version | grep "1.9"` Will this match other versions? I'm imagining in the future having a version like `4.1.9` or something. It might be better to be more strict on what versions we consider 1.9.

Actually, looking at the code again I'm not even sure that expression is correct. With:
```
local ruby_1_9=$ruby_version | grep "1.9"
```
Grep won't actually get anything, so it's not actually assigning ruby_1_9 to any useful value.

Also, your if statement shouldn't compare with `==`, `=` is enough in Bash.

**Comment by pioneerskies** [comment]
Just my 2 cents: as far as I can see https://cache.ruby-lang.org/pub/ruby/ lists complete list of ruby version under each `$major.$minor` directory. I'm about to think if it wouldn't be a better, more generalized approach to always get minor and major from the requested version and `GET` from the  dedicated child folder.

**Comment by pioneerskies** [comment]
Consider this just a little more than pseudo-code and an example about my previous comment, pls:

```bash
local ruby_complete_version=$(get_ruby_version $version)
local ruby_minor_version=$(echo $ruby_complete_version | grep -oE "^[0-9].[0-9]")

  
    if [ "${ruby_type}" = "ruby" ]; then
      echo "https://cache.ruby-lang.org/pub/ruby/${$ruby_minor_version}/ruby-${ruby_complete_version}.tar.gz"
```

**Comment by Stratus3D** [comment]
Sorry to have let this PR sit here for so long. We now use ruby-build, so if there is an issue with downloading Ruby versions it should be fixed in ruby-build.

**Pull request closed without merging**
