### PR TITLE
Update ruby-build

### LINKED ISSUE #71: TruffleRuby support
All the other main Ruby version management tools now support TruffleRuby: https://github.com/oracle/truffleruby/blob/master/doc/user/ruby-managers.md#installing-truffleruby-with-rvm-ruby-build-or-ruby-install maybe asdf-ruby should keep in pair with them

### PR DESCRIPTION
**Pull request by mdesantis**
This ruby-build update comes with TruffleRuby support. Fixes #71.

### CODE REVIEW

**Comment by Stratus3D** [comment]
Awesome! Thanks so much!

**Comment by Stratus3D** [comment]
It should upgrade ruby-build automatically when you update `asdf-ruby` and start using it to list or install ruby versions.

**Comment by eregon** [comment]
> It should upgrade ruby-build automatically when you update asdf-ruby and start using it to list or install ruby versions.

@Stratus3D How does that work? Could you point me to the code doing that?

Also see https://twitter.com/o_bahareth/status/1026118970888409088

**Comment by eregon** [comment]
I guess you probably meant with this PR, updating the asdf-ruby plugin will also update ruby-build to the given version.
@Stratus3D  So asdf-ruby doesn't automatically use the latest ruby-build, it needs a PR like this to update, is that right?

**Comment by Stratus3D** [comment]
@eregon correct.

Thinking about this now though, updating automatically might not be ideal. It might make debugging harder (which version of ruby-build was the user using when the error was encountered?) and we'd need to have some logic around determining which versions we should upgrade to (do we always want to upgrade even if there are major, potentially breaking, changes?). What do you think? I'm open to either approach, but I kind of like the explicitness of a hardcoded version. Updating it is pretty easy, even for someone not experienced with the code.

**Comment by eregon** [comment]
Indeed, there are of course trade-offs.

Just as one data point, there are TruffleRuby releases around once per month, so that means to have  the latest TruffleRuby release in `asdf-ruby`, the import would need to be bumped once a month.
I think `ruby-build` is fairly stable, and they mark releases frequently. Maybe a way from `asdf-ruby` to update to the latest `ruby-build` release would be convenient, but I'm not familiar enough with asdf to know if that's a good idea or not.

FWIW, `ruby-install` doesn't suffer from this because it uses [`ruby-versions`](https://github.com/postmodern/ruby-versions) (and can fetch the latest versions on demand). Maybe one way would be to integrate `ruby-versions` in `ruby-build`, then one could just update from `ruby-build` the list of installable Rubies without changing any code. It seems a little bit tricky to integrate it that way though.

**Comment by Stratus3D** [comment]
Yeah it would be nice if we didn't always have to update ruby-build every time a new version is released. But at the same time version bump PRs are easy to create and review.

If it wouldn't be too much work to integrate ruby-versions in asdf-ruby with ruby-build I'd be favor of that. But we'd have to make sure that ruby-versions and ruby-build work together properly, even when ruby-versions knows about a version that ruby-build doesn't. If that's something that will work I'm all for it, otherwise let's just stick with the manual version updates.

**Comment by eregon** [comment]
> If that's something that will work I'm all for it, otherwise let's just stick with the manual version updates.

I think we need to figure out if and how it makes sense to integrate `ruby-versions` in `ruby-build` itself.
In any case, manual updates in asdf-ruby seem fine until then.

**Pull request merged**
