### PR TITLE
Bump ruby-build to version v20231225

### PR DESCRIPTION
**Pull request by f440**

### CODE REVIEW

**Comment by jon-sully** [comment]
🙌 🎄💎

**Comment by bmulholland** [comment]
To install 3.3 before this is merged and released:

`ASDF_RUBY_BUILD_VERSION=a473f444de97353bcc7cfdb0a72b8c41aa35568f asdf install ruby 3.3.0`

[Credit to @vlazar from last year](https://github.com/asdf-vm/asdf-ruby/pull/326#issuecomment-1364660511) -- thank you!

**Comment by dorianmarie** [comment]
Screenshot 2023-12-26 at 10 05 46

**Comment by Stratus3D** [comment]
Sorry for the delay here! Thanks for the PR @f440 !

**Pull request merged**
