### PR TITLE
use https to download ruby source

### LINKED ISSUE #28: Never download over HTTP!
"http://cache.ruby-lang.org" is used in [bin/install](https://github.com/asdf-vm/asdf-ruby/blob/master/bin/install). Not a good idea without other means of ensuring the authenticity …

Ref: https://github.com/asdf-vm/asdf/issues/158

### PR DESCRIPTION
**Pull request by rmoriz**
fixes #28

### CODE REVIEW

**Comment by rmoriz** [comment]
test failure unrelated and caused by an unversioned install of asdf itself 😞

**Comment by rmoriz** [comment]
https://github.com/asdf-vm/asdf/commit/3c449deb978f23aff2dc74eb0679e553d2505b0e

**Comment by rmoriz** [comment]
added a dummy license to fix the test. See #33 to fix this issue. I guess you will have to ask all existing contributors on the LICENSE but IANAL. (I'm happy with MIT)

**Comment by Stratus3D** [comment]
Added the MIT license to the LICENSE file since that is what we are using for all the other asdf-vm supported plugins.

**Comment by Stratus3D** [comment]
Thanks for the fix!

**Pull request merged**
