### PR TITLE
fix: correct handling of `.default-gems` file

### PR DESCRIPTION
**Pull request by Stratus3D**
This PR re-works the solution in #417 so the code does not crash.

@jmschp FYI, I think this is the correct solution.

### CODE REVIEW

**Comment by Stratus3D** [comment]
I tested this locally and it works with a `.default-gems` file that lacks a newline.

**Comment by jmschp** [comment]
@Stratus3D 

In what situation did it crashed?

**Comment by Stratus3D** [comment]
For me, always, because it complained `$line` wasn't set. I'm not sure why, but the script is set to fail if a variable is unset - https://github.com/asdf-vm/asdf-ruby/blob/master/bin/install#L3.

**Comment by jmschp** [comment]
Curious, it didn't fail, when I tested it.
Well its fixed anyway,

Thanks.

**Pull request merged**
