### PR TITLE
Update ruby-build version to ruby 2.7

### PR DESCRIPTION
**Pull request by FumiyaShibusawa**
## summary
As per https://www.ruby-lang.org/ja/news/2019/12/25/ruby-2-7-0-released/  release notes, ruby 2.7 has been released.

### CODE REVIEW

**Comment by psantos10** [comment]
While this PR is not merged yet, you can install Ruby 2.7.0 using the following command:

```
ASDF_RUBY_BUILD_VERSION=master asdf install ruby 2.7.0
```

**Comment by FumiyaShibusawa** [comment]
https://github.com/asdf-vm/asdf-ruby/pull/152#issuecomment-568937273
I wonder if asdf-ruby should default to master, if not any historical reasons.

**Comment by Stratus3D** [comment]
@FumiyaShibusawa yes, we avoid using anything other than tags for ruby-build to ensure changes to ruby-build don't break asdf-ruby without our knowledge. See https://github.com/asdf-vm/asdf-ruby/issues/108

**Comment by FumiyaShibusawa** [comment]
https://github.com/asdf-vm/asdf-ruby/pull/152#issuecomment-569066572
Thank you. That's naruhodo!

**Pull request merged**
