### PR TITLE
Increment ruby-build for Ruby 3.0.0 support

### PR DESCRIPTION
**Pull request by f440**

### CODE REVIEW

**Comment by fny** [comment]
Is there a way to make this dynamic? It's a little crude that someone needs to manually update a file to support a new release.

**Comment by xarthna** [comment]
@fny You can set `ASDF_RUBY_BUILD_VERSION` environment variable to specify `ruby-build` tags if you want a version before it gets bumped in this repo.

```
ASDF_RUBY_BUILD_VERSION=v20201225 asdf install ruby 3.0.0
```

**Comment by vsyrovat** [comment]
Typing `ASDF_RUBY_BUILD_VERSION=v...` is useless shit because major point of asdf itself is to get all available language versions with minimal effort.

How to make this feature dynamic?
Add
```
export ASDF_RUBY_BUILD_VERSION=master
```
just after enabling asdf lines in your `.bashrc` file.

@fny FYI

**Comment by ne-sachirou** [comment]
This discussion sounds great. But I think the first mission of this plugin is to provide variety of Ruby installations quickly for asdf users. So first please merge this pull request as usual then continue the discussion.

And I think Renovate helps this situation https://docs.renovatebot.com/configuration-options/#regexmanagers .

**Comment by nadavshatz** [comment]
> Is there a way to make this dynamic? It's a little crude that someone needs to manually update a file to support a new release.

we can add a github action that does this on a cron schedule every day and updates as needed.

**Comment by ashmckenzie** [comment]
Tested building 3.0.0 on macOS M1 and worked 🙂:+1:

**Comment by Stratus3D** [comment]
Sorry for the late merge everyone. We've still update this version manually so that no breaking changes from ruby-build break asdf-ruby. I'm sorry for the inconvenience, but I think the tradeoff is worth it.

**Pull request merged**
