### PR TITLE
Bump ruby-build version to v20241105

### PR DESCRIPTION
**Pull request by zavan**
https://github.com/rbenv/ruby-build/releases/tag/v20241105

### CODE REVIEW

**Comment by zavan** [comment]
While this isn't merged you can install Ruby v3.3.6 with `ASDF_RUBY_BUILD_VERSION=v20241105 asdf install ruby 3.3.6`

**Comment by n-rodriguez** [comment]
ping @Stratus3D thank you!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by raldred** [comment]
Is there a solution so that the plugin automatically uses the latest ruby-build without needing patching?

**Comment by zavan** [comment]
> Is there a solution so that the plugin automatically uses the latest ruby-build without needing patching?

You can setup your shell to export `ASDF_RUBY_BUILD_VERSION=master`

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news? ping @Stratus3D

**Comment by Stratus3D** [comment]
Thanks for the PR @zavan ! Sorry for the late merge here.

**Pull request merged**
